version: '3.8'

services:
  app:
    build: .
    container_name: redis-project
    restart: always
    ports:
      - "4002:4002"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    networks:
      - app_network


  redis:
    image: redis:alpine
    container_name: redis-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data: